### ISSUE TITLE
Min flush time higher than default in `batch()`

### ISSUE THREAD

**Issue by leebenson** [timberio/timber-js#13]
https://github.com/timberio/timber-js/blob/851d30243a7d53d1395236272142adc6737f4a19/packages/tools/src/batch.ts#L26

`MIN_FLUSH_TIMEOUT` is set to `1000`, but defaults here to `100`.

Should that be instead:

```
makeBatch(size: number, flushTimeout: number = MIN_FLUSH_TIMEOUT)
```

?

**Comment by aks-** [comment]
aha, correct, thanks for the catch. Will fix it.
