### ISSUE TITLE
Is Deferred necessary?

### ISSUE THREAD

**Issue by leebenson** [timberio/timber-js#14]
From what I can tell, the [Deferred](https://github.com/timberio/timber-js/blob/aks--add-feature-batch/packages/tools/src/deferred.ts#L4-L19) class exists to expose the Promise `resolve` and `reject` methods externally, and is used like this:

https://github.com/timberio/timber-js/blob/851d30243a7d53d1395236272142adc6737f4a19/packages/tools/src/batch.ts#L86-L100

I think this can be simplified by removing the Deferred class entirely, and replacing the block with:

```typescript
return async function<T>(log: T): Promise<any> {
  return new Promise(async (resolve, reject) => {
    buffer.push({ log, resolve, reject });

    if (buffer.length >= size || buffer.length === MAX_BUFFER_SIZE - 1) {
      await flush();
    } else {
      await setupTimeout();
    }

    return resolve;
  });
};
```

**(Note: `val` is replaced with `log` in the `flush()` function)**

@aks-, do you see any issue with this approach that I'm not considering?

**Comment by aks-** [comment]
@leebenson Seems perfect to me. I will push commits once you finish review. Thanks again!
