### ISSUE TITLE
Add retry logic

### ISSUE THREAD

**Issue by leebenson** [timberio/timber-js#2]
In the Observable pipeline, logs flow forward until they are pushed to the subscriber.

Need to add some logic to the subscribe handler in the event of the request to Timber.io failing or throwing an error, to reinsert failed logs back into the pipeline.

**Comment by leebenson** [comment]
The Observables piece is no longer relevant, but some retry logic in the sync method to re-attempt broken network connections still makes sense.

This could possibly be a dedicated `retry()` function added to `@timberio/tools`, or just a loop with some kind of back-off around the actual sync piece. Ideally, this should be user-definable on `ITimberOptions`.

@aks-: do you fancy taking a crack at this?

**Comment by aks-** [comment]
@leebenson yep, hoping to finish it today. thanks!

**Comment by leebenson** [comment]
These are some useful requirements of retry logic, per `3.3.3.1 Batching and Buffering Log Data` of the spec:

> Errors while flushing SHOULD NOT affect the stability of the application. In other words, errors with the library code or the remote service should not result in stability issues for the application.
> 
> If the service responds with an HTTP status code in the 500-599 range or encounters a non-HTTP error (for example: a connection is unexpectedly closed), the library MAY retry the same request. The same request SHOULD NOT be retried more than 3 times.
> 
> After 3 attempts the batch should be dropped and new batches should follow the same retry process. The library MUST NOT stop or pause in any way. This ensures that a Timber outage does not result in the permanent pausing of log transmission. In other words, when the Timber service recovers logs will continue to flow into the developer's Timber account.
