### ISSUE TITLE
Add optional I/O write stream for sync'd logs

### ISSUE THREAD

**Issue by leebenson** [timberio/timber-js#29]
Per https://github.com/timberio/library-specification/blob/master/SPECIFICATION.MD#332-io-device-formatter

For example -

This could be a function that takes a stream:

```
// Only the Node.js lib...
timber.writeStream(someStream)
```

... which will then be piped to _at time of syncing_.

Or perhaps the API could be more stream-like on the `timber` instance directly:

```
timber.pipe(writeStream)
```

... which would then allow all of the usual stream functions (including - in an upcoming/separate issue - the notion of reading from a stream as a form of log ingestion.)

@aks- open to your thoughts.

**Comment by aks-** [comment]
I'm not sure what you mean by 'pipe at time of sync' ... could you please expand on that some more? I assume you mean after logs are synced with timber, we write to the previously piped stream.

**Comment by leebenson** [comment]
> I assume you mean after logs are synced with timber, we write to the previously piped stream.

Yes, exactly.

If we opt for an API that looks like this:

```
timber.writeStream(someStream)
```

Then when a log is synced, a copy of that log would be sent to the stream passed to `.writeStream()`.

This would allow a user to create, say, a file stream, and have each log synced to that stream so that it can be written to disk.

Ideally, the API should match what a user expects from a regular Node stream. We should be able to both read _and_ write to the Timber instance; reading = getting a copy of the synced stream, writing = initiating `.log()` whenever a streamed log comes in.

Eventually, this can then be used as part of the transport for plugins over Bunyan, Winston, etc.

**Comment by aks-** [comment]
Perfect, would love to work on this one.
