### ISSUE TITLE
Add support for logging error objects via log.error()

### ISSUE THREAD

**Issue by danielvaijk** [timberio/timber-js#38]
log.error() can't handle logging error objects? I get an empty object '{}' as the message if I pass an error object.

I would expect to see the error stack logged in Timber when passing, for instance, something like log.error(new Error("example")).

**Comment by leebenson** [comment]
I'm working on this right now. Should go live today. Will update here when done 👍

**Comment by leebenson** [comment]
Rudimentary `Error` handling has been added in [v0.30.0](https://github.com/timberio/timber-js/releases/tag/v0.30.0).

This should work:

```js
const e = new Error("This is a sample error");

timber.error(e); // <-- `message` will be per the message above... and `{ context: { stack: e.stack }}` will be added automatically
```

Error handling has been added to [`@timberio/core`](https://github.com/timberio/timber-js/tree/master/packages/core), so this should work in all environments.

I'd like to flesh this out a bit more in an upcoming version. Currently, the stack trace is a string; this could be improved to be individual lines/code snippets. In the Node version, we can also extract richer meta data on `SystemError` classes.

For now though, the above should get you started!
